[package]
name = "cross-calculations-core"
version = "0.1.0"
edition = "2021"

[dependencies]
rust-extensions = { tag = "0.1.4", git = "https://github.com/MyJetTools/rust-extensions.git" }
serde = { version = "*", features = ["derive"] }
